apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-5myr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-5myr
    app.kubernetes.io/part-of: tkrw-pr714-0075-0003-app
  name: devfile-sample-5myr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-5myr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-5myr
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0003-tenant/tkrw-pr714-0075-0003-app/devfile-sample-5myr@sha256:7e24418fd61300d698b83d7c4cb87ae4cc82218255533813985ec09b23cf9e33
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
